db:
  image: postgres

appsvr:
  build: ./app
  volumes:
    - ./app:/opt/app
  ports:
    - "8001:8001"
  links:
    - db

nginx:
  restart: always
  build: ./nginx
  ports:
    - "8000:8000"
  volumes:
    - /www/public
  volumes_from:
    - appsvr
  links:
    - appsvr:appsvr
