db:
  image: postgres:latest
  restart: always
  volumes:
    - /var/lib/postgresql
  ports:
    - "5432:5432"

appsvr:
  build: ./app
  command: bash -c "sleep 3 && python manage.py runserver 0.0.0.0:8000"
  volumes:
    - ./app:/opt/app
  ports:
    - "8000:8000"
  links:
    - db
