db:
  image: postgres

appsvr:
  build: ./app
  volumes:
    - ./app:/src/app
    - /opt/app
  links:
    - db

nginx:
  build: ./nginx
  ports:
    - "8000:8000"
  volumes:
    - ./app:/src/app
  volumes_from:
    - appsvr
  links:
    - appsvr
